---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  sampleQpolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - "https://sqs:us-east-2.amazonaws.com/444455556666/queue1"
        - "https://sqs:us-east-2.amazonaws.com/444455556666/queue2"
      PolicyDocument:
        Id: samplesnspolicy
        Version: '2012-10-17'
        Statement:
        - Sid: szimplepolicy1
          Action:
            - "SQS:SendMessage"
            - "SQS:ReceiveMessage"
          Effect: "Allow"
          Principal: "*"

  AlarmNumMessagesExceedsThreshold:
    Type: AWS::CloudWatch::Alarm
    DependsOn: SQSQueueProduct
    Properties:
      AlarmName: !Join [ "-", [ "sqs", !Ref QueueName, "num-exceeded" ] ]
      AlarmDescription: 'CloudWatch Alarm'
      AlarmActions: 
        - !Join [ ":", [ "arn:aws:sns", !Ref AWS::Region, !Ref AWS::AccountId , "Direct-Customer-Alerts"  ] ]
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessages
      Dimensions:
        - Name: "QueueName"
          Value: !Ref QueueName
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2    
      Period: 300              
      Statistic: SampleCount   
      Threshold: !Ref AlarmNumMessageReceivedThreshold  # Desired threshold of approx. number of messages received


